### ISSUE TITLE
Dosen't work.

### ISSUE THREAD

**Issue by FrozenPlace** [metaspook/ViPER4Windows-Patcher#1]
V4W(v1.0.5) still doesn't work after I ran this .bat and rebooted my device.
Even more unfortunately, my headset(Logitech G633) is not supported of both DTS and Dobly Atoms as well. 
I'm gonna say it again in chinese, because V4W is a chinese software.
---------------------------------------------------------------------------
在我运行了这个批处理并重启电脑之后，V4W（v1.0.5）非但没有正常运行，还导致了我的耳机（罗技G633）失去了DTS和杜比（Dobly Atoms）音效的支持。
建议打算尝试这个批处理的后来者先预先备份注册表以防不测。

**Comment by metaspook** [comment]
Install Freshly Windows 10 > Install/Update audio driver what by default found by Windows 10 if u connected to the Internet > Apply the patch > reboot
