### ISSUE TITLE
Now working with Latest windows 11 22000.71 developer build

### ISSUE THREAD

**Issue by Rams225** [metaspook/ViPER4Windows-Patcher#10]
It used to work on previous builds but now it is not working on the latest builds tried all the registry patch files nothing worked.

**Comment by biexiang** [comment]
the same,it not working in my windows 11 device

**Comment by martjay** [comment]
me too

**Comment by metaspook** [comment]
> It used to work on previous builds but now it is not working on the latest builds tried all the registry patch files nothing worked.



> the same,it not working in my windows 11 device



> me too

issue fixed !!! checkout the new version..

**Comment by martjay** [comment]
> > It used to work on previous builds but now it is not working on the latest builds tried all the registry patch files nothing worked.
> 
> > the same,it not working in my windows 11 device
> 
> > me too
> 
> issue fixed !!! checkout the new version..

Well done bro, u r the best!

**Comment by metaspook** [comment]
> > > It used to work on previous builds but now it is not working on the latest builds tried all the registry patch files nothing worked.
> > 
> > 
> > > the same,it not working in my windows 11 device
> > 
> > 
> > > me too
> > 
> > 
> > issue fixed !!! checkout the new version..
> 
> Well done bro, u r the best!

Thanks..🥰 can connect with me @ Telegram https://t.me/metaspook
