### ISSUE TITLE
No sound, after applying this patch

### ISSUE THREAD

**Issue by Shob8sayala** [metaspook/ViPER4Windows-Patcher#2]
I installed Viper4windows, restarted the pc... The installed this patch. But after restarting there is no sound in my PC

**Comment by metaspook** [comment]
Install Freshly Windows 10 > Install/Update audio driver what by default found by Windows 10 if u connected to the Internet > Apply the patch > reboot

**Comment by metaspook** [comment]
@Shob8sayala
try the new release

**Comment by LRonHorse** [comment]
How can I uninstall the registry entries applied by this patch to get my pc back to normal

**Comment by metaspook** [comment]
> How can I uninstall the registry entries applied by this patch to get my pc back to normal

Just uninstall fully VIper4Windows from ur PC then.... if u have any Audio mod or driver like Realtek, DTS, Dolby Atmos etc u can install them...
