### ISSUE TITLE
Audio delay introduced after running the patcher

### ISSUE THREAD

**Issue by alecfs24** [metaspook/ViPER4Windows-Patcher#3]
So I only just noticed this very recently, and at first, I thought it was Bluetooth being Bluetooth and suffering from some delay since that's what I had been using for a while. But then when I went and watched some youtube with my wired headphones, that's when I knew something was up. I verified it, and its definitely not the browser, or anything else, but after I run the patcher, it causes a delay. it fixes V4W, but this new problem is a rather big one for me.

**Comment by alecfs24** [comment]
Ok so I reinstalled it again, after removing my audio driver, (high def audio driver, not realtek or anything) and this time, the issue would go away when v4w was turned off, but in previous instances, it did not go away when it was turned off, just FYI.

**Comment by metaspook** [comment]
@alecfs24  Although You know it's getting hard if the original developer of ViPER4Windows not continue developing their software ... so I'm going to work as far I can in some days..update this patcher.. get subscribed..
